### ISSUE TITLE
MeSH Hierarchical CSV file

### ISSUE THREAD

**Issue by KuleenS** [insilicomedicine/DILBERT#1]
Hello!

I am a medical NLP researcher who is looking to use your model for some tasks. I wanted to run the MeSH Hierarchical Sampling pipeline for processing the data. However, looking through the datasets provided, it seems to be missing. Could you please provide the file? If there are some licensing issues, could you send the script to create the file?

Thanks,

Kuleen

**Comment by dartrevan** [comment]
Hello, Kuleen!

I've created PR with a script that could be used for hierarchy file generation. It has two arguments:
1) --input_file which is d2022.bin file from here https://nlmpubs.nlm.nih.gov/projects/mesh/MESH_FILES/asciimesh/
2) --save_to where to save hierarchy file
The output of this script you can use for Hierarchical Sampling.

**Comment by KuleenS** [comment]
Thanks!
